from abc import ABC, abstractmethod

from aiosqlite import Connection
from src.data.models import Recommendation, RecommendationPetDescription


class BaseLLMRecommender(ABC):
    """Abstract class that all recommenders must implement.

    Parameters
    ----------
    connection : Connection
        Connection to the database.
    """

    def __init__(self, connection: Connection) -> None:
        super(BaseLLMRecommender, self).__init__()
        self.connection = connection

    @abstractmethod
    async def recommend(
        self, description: RecommendationPetDescription
    ) -> Recommendation:
        """Reccomend a food to a pet based on a description.

        Parameters
        ----------
        description : RecommendationPetDescription
            Description that must suit a recommended product.

        Returns
        -------
        Recommendation
            Recommendation generated by model.
        """
